TebLocalPlannerROS:

 odom_topic: odom
 map_frame: map 
    
 # Trajectory
  
 teb_autosize: True
 dt_ref: 0.5 
 dt_hysteresis: 0.2 
 global_plan_overwrite_orientation: True
 max_global_plan_lookahead_dist: 2.0   # Step 3b(IV): 3b(I) + 3b(III) + lookahead distance from 2.0 to 3.0
 feasibility_check_no_poses: 5

 publish_feedback: true
    
 # Robot

 max_vel_x: 0.6           # Step 3b(I): velocity from 0.6 to 0.9
 max_vel_x_backwards: 0.3 # Step 3b(I): backwards vel from 0.3 to 0.5
 max_vel_theta: 0.3       # Step 3b(I): max vel theta from 0.3 to 0.6
 acc_lim_x: 0.1           # Step 3b(I): acc lim x from 0.1 to 0.4
 acc_lim_theta: 0.3       # Step 3b(I): backwards vel from 0.3 to 0.5
 min_turning_radius: 0.0
 footprint_model: 
  type: "polygon"


  vertices: [[0.15, -0.15], 
            [-0.15, -0.15], 
            [-0.15, 0.15], 
            [0.15, 0.15]]
          
 # GoalTolerance

 xy_goal_tolerance: 0.15    # Step 3b(IV): 3b(I) + 3b(III) + xy goal tolerance from 0.15 to 0.50
 yaw_goal_tolerance: 0.15   # Step 3b(IV): 3b(I) + 3b(III) + yaw goal tolerance from 0.15 to 0.50
 free_goal_vel: False
    
 # Obstacles
    
 min_obstacle_dist: 0.10    # Step 3b(IV): 3b(I) + 3b(III) + min obstacle distance from 0.10 to 0.25
 include_costmap_obstacles: True
 costmap_obstacles_behind_robot_dist: 1.0
 obstacle_poses_affected: 20 
 costmap_converter_plugin: "" 
 costmap_converter_spin_thread: True
 costmap_converter_rate: 5
 inflation_dist: 0.1
 include_dynamic_obstacles: false

 # Optimization
    
 no_inner_iterations: 3 
 no_outer_iterations: 2 
 optimization_activate: True
 optimization_verbose: false
 penalty_epsilon: 0.04 
 weight_max_vel_x: 2
 weight_max_vel_theta: 1
 weight_acc_lim_x: 1
 weight_acc_lim_theta: 1
 weight_kinematics_nh: 1000
 weight_kinematics_forward_drive: 200.0 
 weight_kinematics_turning_radius: 1
 weight_optimaltime: 1
 weight_obstacle: 100 
 weight_dynamic_obstacle: 10 
 selection_alternative_time_cost: False 

 # Homotopy Class Planner

 enable_homotopy_class_planning: False 
 enable_multithreading: True
 simple_exploration: False
 max_number_classes: 4 
 roadmap_graph_no_samples: 15
 roadmap_graph_area_width: 5
 h_signature_prescaler: 0.5
 h_signature_threshold: 0.1